In [10]:
import numpy as np
n_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
n = np.array(n_list)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
n1 = np.zeros((5,6))
print(n1)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [12]:
n2 = np.ones((5,5))
print(n2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
n3 = np.arange(0, 10, 3)
print(n3)

[0 3 6 9]


In [19]:
matrix = np.array([1,3,5,7,6,5,6,8,7])
matrix = matrix.reshape(3,3)
print(matrix)
print('shape:', matrix.shape)
print('dtype:', matrix.dtype)

[[1 3 5]
 [7 6 5]
 [6 8 7]]
shape: (3, 3)
dtype: int64


In [25]:
# выводим второй и последний элемент списка
print(n_list[1])
print(n_list[-1])

1
9


In [23]:
# выводим со второго до пятого невключительно элементы списка
print(n_list[2:5])

[2, 3, 4]


In [29]:
# срезом получаем второй элемент второй строки
print(matrix[1,1])

6


In [22]:
# срезом получаем вторую строку
print(matrix[1:2])

[[7 6 5]]


In [34]:
# выводим все строки первого столбца
print(matrix[:, 0])

[1 7 6]


In [36]:
# выводим все столбцы первой строки
print(matrix[0, :])

[1 3 5]


In [38]:
# выводим подмассив
print(matrix[0:2, 0:2])

[[1 3]
 [7 6]]


In [41]:
arrange_1 = np.array([1,3,5,7])
arrange_2 = np.array([2,4,6,8])
# сумма
sum = arrange_1 + arrange_2
print(sum)
# умножение
mul = arrange_1 * arrange_2
print(mul)
# сумма
sum = arrange_1 + arrange_2
print(sum)
# степень
pow = arrange_1 ** 2
print(pow)

[ 3  7 11 15]
[ 2 12 30 56]
[ 3  7 11 15]
[ 1  9 25 49]


In [46]:
mean = arrange_1.mean()
print(mean)
mean1 = np.mean(arrange_1)
print(mean1)

4.0
4.0
